### ISSUE TITLE
trained model

### ISSUE THREAD

**Issue by Carinazhao22** [ygtxr1997/MSML#1]
Hello,

Thanks for sharing the codes! I want to run the test file. is it possible to provide the weight folder of A18_msml? also, I'm wondering where I can get access to MFV datasets. thanks!

**Comment by ygtxr1997** [comment]
Now we provide the pre-trained model. Please refer to [https://github.com/ygtxr1997/MSML#testing](https://github.com/ygtxr1997/MSML#testing).
You shoud apply for MFV datasets on [https://pkuml.org/resources/pku-masked-face-dataset.html](https://pkuml.org/resources/pku-masked-face-dataset.html).

**Comment by Carinazhao22** [comment]
Hi,
Thanks for sharing!  I have sent the access request for pre-trained model as carinazhao2328. May you give the approval for the request? Thanks

**Comment by ygtxr1997** [comment]
Now I open the Google Drive for any one who gets the link. You can check it.
MFV dataset belongs to Peking University. I'm not the owner. You shoud wait for them to reply your e-mail.
