### ISSUE TITLE
testing datasets

### ISSUE THREAD

**Issue by jiejie22997** [ygtxr1997/MSML#3]
Hello,

i have tried to run the test.py with LFW on the provided model. It seems we need to generate bin file for LFW. What is the format and how can I generate that? Thanks in advance!

**Comment by ygtxr1997** [comment]
We use the .bin files provided by [insightface](https://github.com/deepinsight/insightface). 
In the Data Preparation section of our [README](https://github.com/ygtxr1997/MSML#data-preparation), you can find the link.
Both [CASIA](https://github.com/deepinsight/insightface) and [MS1M](https://github.com/deepinsight/insightface) training datasets contain the .bin files you need.

**Comment by jiejie22997** [comment]
got it, thanks!
