### ISSUE TITLE
the requirements of the code running environment

### ISSUE THREAD

**Issue by amycao123** [ygtxr1997/MSML#7]
Could you please give a list of versions of the software packages required for the current code running environment？

**Comment by ygtxr1997** [comment]
We just uploaded the 'requirements.txt' file generated by `pip freeze`.
You can refer to this link: [https://github.com/ygtxr1997/MSML/blob/main/requirements.txt](https://github.com/ygtxr1997/MSML/blob/main/requirements.txt)

**Comment by amycao123** [comment]
Thank you very much for your help.
